slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    resolution: 0.05
    transform_publish_period: 0.02
    map_update_interval: 2.0
    minimum_time_interval: 0.5
    use_scan_matching: true
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
