controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    
    # Only joint state broadcaster - VESC handles actual control
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_to_back_left_wheel
      - base_to_back_right_wheel
      - base_to_front_left_hinge
      - base_to_front_right_hinge
      - front_left_hinge_to_wheel
      - front_right_hinge_to_wheel